### ISSUE TITLE
Wrong mask being called from template flow

### ISSUE THREAD

**Issue by eilidhmacnicol** [nipreps/nirodents#24]
- [ ] Requires updating some of the images on template flow ( @oesteban ):
- remove `tpl-WHS_res-?_atlas-v3_desc-origBrain_mask.nii.gz`
- add a downsampled (0.1 x 0.1 x 0.1) version of cerebrum labels and mask, i.e.: `tpl-WHS_res-2_atlas-v3_cerebrum_dseg.nii.gz` and `tpl-WHS_res-2_atlas-v3_desc-cerebrum_mask.nii.gz`
- `tpl-WHS_res-?_atlas-v3_desc-brain_mask.nii.gz` ->`tpl-WHS_res-?_atlas-v3_desc-origBrain_mask.nii.gz`
- `tpl-WHS_res-?_desc-brain_mask.nii.gz` -> `tpl-WHS_res-?_atlas-v3_desc-brain_mask.nii.gz`

- [x] Requires updating brainextraction.py to call correct masks ( @eilidhmacnicol )

**Comment by oesteban** [comment]
@eilidhmacnicol can you please open an issue at https://github.com/templateflow/tpl-WHS/issues/new to request the removal of `tpl-WHS_res-?_atlas-v3_desc-origBrain_mask.nii.gz` ?
