### ISSUE TITLE
problems with Nirodents installation in Docker - Apple Silicon

### ISSUE THREAD

**Issue by Pomierny** [nipreps/nirodents#64]
### What happened?

Hi after creating a docker image I am having such error:

(base) bartoszpomierny@MBPBP nirodents % docker run -it bartoszpomierny/fmriprep-rodents:dev
Traceback (most recent call last):
 File "/opt/conda/bin/artsBrainExtraction", line 8, in <module>
  sys.exit(main())
 File "/src/nirodents/nirodents/cli/brainextraction.py", line 131, in main
  from ..workflows.brainextraction import init_rodent_brain_extraction_wf
 File "/src/nirodents/nirodents/workflows/brainextraction.py", line 17, in <module>
  from niworkflows.interfaces.bids import DerivativesDataSink as _DDS
ModuleNotFoundError: No module named 'niworkflows' 

### What command did you use?

```shell
docker run -it
```

### What version of the software are you running?

latest

### How are you running this software?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by gdevenyi** [comment]
You should check if you're running an apple arm docker image or x86_64. Some packages probably don't exist for arm and so the docker container is broken. This is a common apple silicon problem

**Comment by eilidhmacnicol** [comment]
The dockerfile is in the old style; this needs updating anyway, but niworkflows is indeed missing from this version of the dockerfile

**Comment by Pomierny** [comment]
@gdevenyi  yes - linux/arm64 image is set
